### ISSUE TITLE
any plans on adding the WSO2 API Manager to the list?

### ISSUE THREAD

**Issue by scotthsieh0503** [fgimenez/soa-tools-cookbook#1]
This is super useful especially for a developer that does not know much about server set up like me.  I am currently trying to get WSO2 API Manager to work in Vagrant with Multi-tendant but does not see to have much luck.

**Comment by fgimenez** [comment]
@scotthsieh0503 thanks a lot for your comments :)

Currently I don't have time to spend in improving this, PR's are more than welcome.

Cheers,
